# Generated by Django 2.0.4 on 2018-04-09 16:50

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', django.contrib.postgres.fields.jsonb.JSONField()),
                ('compile_opts', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_opts', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('train_on_gpu', models.BooleanField(default=False)),
                ('y_pred', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), blank=True, null=True, size=None)),
                ('history', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('evaluation', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('exec_time', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('model_filepath', models.FilePathField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.SentenceBatch')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='keras_ml.Model')),
            ],
            options={
                'db_table': 'keras_ml_train_session',
            },
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('config', 'compile_opts')},
        ),
    ]
