# Generated by Django 2.0.4 on 2018-04-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keras_ml', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainsession',
            name='evaluation',
        ),
        migrations.AddField(
            model_name='trainsession',
            name='f1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainsession',
            name='precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainsession',
            name='recall',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
