# Generated by Django 2.0.4 on 2018-04-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keras_ml', '0002_auto_20180416_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainsession',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
