# Generated by Django 2.0.4 on 2018-04-07 20:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.TextField(unique=True)),
                ('text', models.TextField()),
                ('out_of_scope', models.BooleanField()),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('polarities', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
            options={
                'db_table': 'test_sentences',
            },
        ),
        migrations.CreateModel(
            name='TrainSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.TextField(unique=True)),
                ('text', models.TextField()),
                ('out_of_scope', models.BooleanField()),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('polarities', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
            options={
                'db_table': 'train_sentences',
            },
        ),
    ]
