# Generated by Django 2.0.4 on 2018-04-08 02:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word_embeddings', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preprocessing', models.SmallIntegerField(choices=[(-1, 'No preprocessing'), (1, 'Preprocessing v1')])),
                ('processing', models.SmallIntegerField(choices=[(-1, 'No processing'), (1, 'Word2vec indexes v1')])),
                ('x_train_raw', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('x_train_preproc', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('y_train_raw', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('x_train', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), blank=True, size=None)),
                ('y_train', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('x_test_raw', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('x_test_preproc', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('y_test_raw', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('x_test', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), blank=True, size=None)),
                ('y_test', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
            ],
            options={
                'db_table': 'sentence_batch',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'Aspect detection'), (2, 'Polarity detection')])),
                ('aspect_entity', models.TextField(blank=True)),
                ('aspect_attribute', models.TextField(blank=True)),
                ('polarity', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnknownWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('morph_analyzer', models.TextField(choices=[(-1, 'Unknown'), (1, 'Pymorphy2')], default=-1)),
            ],
            options={
                'db_table': 'data_unknown_word',
            },
        ),
        migrations.AlterModelTable(
            name='testsentence',
            table='data_test_sentences',
        ),
        migrations.AlterModelTable(
            name='trainsentence',
            table='data_train_sentences',
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('type', 'aspect_entity', 'aspect_attribute', 'polarity')},
        ),
        migrations.AddField(
            model_name='sentencebatch',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Task'),
        ),
        migrations.AddField(
            model_name='sentencebatch',
            name='w2v_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='word_embeddings.Word2Vec'),
        ),
    ]
